### ISSUE TITLE
Instantiation

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/wredProfile#10]
There is a problem in instantiating a Profile, if no instance that could be cloned would already exist.
Particularly, since the capabilities are attached to the instances of Profile.

**Potential Solution:**
- If not assured that there is always at least one instance of Profile, an RPC shall be defined.
- This RPC shall 
  - either generate a default Profile, which can serve as a prototype for clones, 
  - or create and edit actual instances of Profile.

**Comment by openBackhaul** [comment]
An [RPC based solution has been defined in the SchedulerProfile](https://github.com/openBackhaul/schedulerProfile/issues/2#issuecomment-1361194600).
It covers
- creating an instance
- modifying an existing instance
- deleting an instance

Would it make sense to replicate this solution here?

**Comment by demx8as6** [comment]
**Decision during the 5G-xhaul call on 22nd of March 2023:** 
_[Proposal to the 5G-xhaul call on 15th of March 2023 has been rephrased in the section marked in bold and italic.]._

The following changes shall be made to the UML modelling of the WredProfile:

An Interface of name WredProfileOperations shall be created.

An Operation of name **createWredProfile** shall be created.
It shall NOT be idempotent, but create a new instance of WredProfile with every call.
It shall be atomic.
**_It shall have the following input parameters that must be provided with every call (attributes that are not supported by the device, will be ignored):_**
- externalLabel:String [1] with comment "Identifier of the instance of WredProfile. Could be a name, could be a number. Free text field to be filled by the operator.".
- thresholdLow:Integer [1] with comment "Defines the lower threshold in Byte. When average queue content is exceeding this value, packets start getting dropped. Probability of dropping is linear increasing until it reaches the value configured in dropProbabilityAtThresholdHigh when average queue content reaches thresholdHigh.".
- dropProbabilityAtThresholdLow:Integer [1] with comment "Only relevant if (dropProbabilityAtLowThresholdIsAvail==true). Defines the probability (as a percentage) of an incoming packet getting dropped when the content of the queue reaches the low threshold.".
- thresholdHigh:Integer [1] with comment "Defines the upper threshold in Byte.  When average queue content is reaching this value, incoming packets are dropped with the probability configured in dropProbabilityAtThresholdHigh. When average queue content is exceeding this value, all incoming packets get dropped.".
- dropProbabilityAtThresholdHigh:Integer [1]  with comment "Defines the probability (as a percentage) of an incoming packet getting dropped when the content of the queue reaches the upper threshold.".
- gentleWredIsOn:Boolean [1] with comment "Only relevant if (gentleWredIsAvail==true). true = The drop probability is linear increasing between dropProbabilityAtThresholdHigh and 100% at thresholdGentle (otherwise drop probability jumps to 100% at thresholdHigh).".
- thresholdGentle:Integer [1] with comment "Only relevant if (gentleWredIsAvail==true) AND (gentleWredIsOn==true). Defines the 100% dropping threshold for gentle WRED in Byte.  When average queue content reaches or exceeds this value, incoming packets get dropped with 100% probability.".
- sensitivity:Integer [1] with comment "Only relevant if (sensitivitySettingIsAvail==true). Defines how sensitive WRED reacts on traffic burst. low values = WRED reacts quickly and is sensitive to short bursts. high values = WRED reacts slowly on short bursts, which could result in buffer overflow and tail drop. Values between 0 and 15.".
- coloringIsOn:Boolean [1] false with comment "Only relevant if (colloringIsAvail==true). true = Exceeding packets are marked yellow instead of being immediately discarded.".

It shall have the following output parameter:
_createdWredProfile :: Profile [1] with comment "UUID of the instance of WredProfile that has been newly created."


An Operation of name **modifyWredProfile** shall be created.
It shall be idempotent
It shall be atomic
It shall have the following mandatory input parameter:  
- _wredProfileToBeModified [1] with a reference to an existing Profile with Profile(ProfileNameType==PROFILE_NAME_TYPE_WRED_PROFILE)  

It shall have the following optional input parameters (if not provided, the configured values shall not be touched):  
- externalLabel:String [0..1] = 'External label not yet defined.' with comment "Identifier of the instance of WredProfile. Could be a name, could be a number. Free text field to be filled by the operator.".
- thresholdLow:Integer [0..1] = -1 with comment "Defines the lower threshold in Byte. When average queue content is exceeding this value, packets start getting dropped. Probability of dropping is linear increasing until it reaches the value configured in dropProbabilityAtThresholdHigh when average queue content reaches thresholdHigh.".
- dropProbabilityAtThresholdLow:Integer [0..1] = -1 with comment "Only relevant if (dropProbabilityAtLowThresholdIsAvail==true). Defines the probability (as a percentage) of an incoming packet getting dropped when the content of the queue reaches the low threshold.".
- thresholdHigh:Integer [0..1] = -1 with comment "Defines the upper threshold in Byte.  When average queue content is reaching this value, incoming packets are dropped with the probability configured in dropProbabilityAtThresholdHigh. When average queue content is exceeding this value, all incoming packets get dropped.".
- dropProbabilityAtThresholdHigh:Integer [0..1] = -1 with comment "Defines the probability (as a percentage) of an incoming packet getting dropped when the content of the queue reaches the upper threshold.".
- gentleWredIsOn:Boolean [0..1] = false with comment "Only relevant if (gentleWredIsAvail==true). true = The drop probability is linear increasing between dropProbabilityAtThresholdHigh and 100% at thresholdGentle (otherwise drop probability jumps to 100% at thresholdHigh).".
- thresholdGentle:Integer [0..1] = -1 with comment "Only relevant if (gentleWredIsAvail==true) AND (gentleWredIsOn==true). Defines the 100% dropping threshold for gentle WRED in Byte.  When average queue content reaches or exceeds this value, incoming packets get dropped with 100% probability.".
- sensitivity:Integer [0..1] = -1 with comment "Only relevant if (sensitivitySettingIsAvail==true). Defines how sensitive WRED reacts on traffic burst. low values = WRED reacts quickly and is sensitive to short bursts. high values = WRED reacts slowly on short bursts, which could result in buffer overflow and tail drop. Values between 0 and 15.".
- coloringIsOn:Boolean [0..1] = false with comment "Only relevant if (colloringIsAvail==true). true = Exceeding packets are marked yellow instead of being immediately discarded.".


An Operation of name **deleteWredProfile** shall be created.
It shall be idempotent
It shall be atomic
It shall have the following input parameter:
- _obsoleteWredProfile :: Profile [1] with a reference to an existing Profile with Profile(ProfileNameType==PROFILE_NAME_TYPE_WRED_PROFILE) and comment "UUID of the instance of WredProfile that shall be deleted."


The **existing modelling** shall be changed in the following aspects:
- WredProfile_Pac::_wredProfileConfiguration shall change from read/write to read-only
- WredProfileConfiguration::externalLabel shall change from read/write to read-only
- WredProfileConfiguration::thresholdLow shall change from read/write to read-only
- WredProfileConfiguration::dropProbabilityAtThresholdLow shall change from read/write to read-only
- WredProfileConfiguration::thresholdHigh shall change from read/write to read-only
- WredProfileConfiguration::dropProbabilityAtThresholdHigh shall change from read/write to read-only
- WredProfileConfiguration::gentleWredIsOn shall change from read/write to read-only
- WredProfileConfiguration::thresholdGentle shall change from read/write to read-only
- WredProfileConfiguration::sensitivity shall change from read/write to read-only
- WredProfileConfiguration::coloringIsOn shall change from read/write to read-only

**Comment by openBackhaul** [comment]
UML changed as described above.

**Comment by openBackhaul** [comment]
Has been provided in WredProfile_1.0.0-tsi.240104.1945+yang
